apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - standard/league.bexxmodd_com.theleagues.yaml
  - standard/league.bexxmodd_com.standings.yaml
  - standard/league.bexxmodd_com.gameresults.yaml
