apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: theleague
  name: theleague-editor-role
rules:
- apiGroups:
  - bexxmodd.com
  resources:
  - theleagues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bexxmodd.com
  resources:
  - theleagues/status
  verbs:
  - get
- apiGroups:
  - bexxmodd.com
  resources:
  - standings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bexxmodd.com
  resources:
  - standings/status
  verbs:
  - get
- apiGroups:
  - bexxmodd.com
  resources:
  - gameresults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
